In [1]:
import torchvision.models as models
import torch
import torch.nn as nn

import torchvision.transforms as transforms


In [2]:
import itertools

In [5]:
for i in itertools.permutations([1,2,1]):
    print(i)

(1, 2, 1)
(1, 1, 2)
(2, 1, 1)
(2, 1, 1)
(1, 1, 2)
(1, 2, 1)


In [1]:
import numpy as np

In [3]:
a = np.random.randn(70,30,30)

In [4]:
np.delete(a, [1,2], axis=2).shape

(70, 30, 28)

In [5]:
b = np.insert(a, 0, values=0, axis=2)

In [6]:
b[:, : ,0]

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [7]:
state = {}

state[(1,2,3)]={'properties':1, 'state':2}



In [8]:
q,w = zip(*state.items())

In [9]:
q

((1, 2, 3),)

In [10]:
w

({'properties': 1, 'state': 2},)

In [17]:
s = np.array([[0,0,0,0],[0,0,1,0],[1,1,1,1],[0,1,0,0]])

In [18]:
np.argmax(s, axis=0)

array([2, 2, 1, 2])

In [16]:
s.shape

(4, 4)

In [19]:
s = np.zeros((3,3,10))

In [20]:
s[1,2,4]=1

In [21]:
_state = np.argmax(s, axis=2)

In [22]:
_state

array([[0, 0, 0],
       [0, 0, 4],
       [0, 0, 0]])

In [6]:
nu = np.random.randn(10)

In [12]:
np.argwhere(nu>0).reshape(-1)

array([4, 8])

In [13]:
nu

array([-0.19387812, -1.10590125, -1.08581133, -1.59069523,  1.06836908,
       -0.66004983, -2.29743718, -0.94187634,  1.02787919, -0.37699574])

In [14]:
nu[nu>0]

array([1.06836908, 1.02787919])